CREATE TABLE IF NOT EXISTS `prefix_feeds` (
  `row_id` bigint(20) NOT NULL AUTO_INCREMENT,
  `owner_guid` bigint(20) unsigned NOT NULL,
  `story_guid` bigint(20) unsigned NOT NULL,
  `id` bigint(20) unsigned NOT NULL,
  `action_type` varchar(32) NOT NULL,
  `view` text NOT NULL,
  `subject_guid` bigint(20) unsigned NOT NULL,
  `object_guid` bigint(20) unsigned NOT NULL,
  `target_guid` bigint(20) unsigned NOT NULL,
  `annotation_id` int(11) NOT NULL,
  `posted` int(11) NOT NULL,
  `enabled` enum('yes','no') NOT NULL DEFAULT 'yes',
  `access_guid` bigint(20) unsigned NOT NULL,
  `access_owner_guid` bigint(20) unsigned NOT NULL,
  `access_id` int(11) NOT NULL,
  `topic` varchar(255) NOT NULL,
  `type` varchar(8) NOT NULL,
  `subtype` varchar(32) NOT NULL,
  PRIMARY KEY (`row_id`),
  KEY `owner_guid` (`owner_guid`),
  KEY `story_guid` (`story_guid`),
  KEY `id` (`id`),
  KEY `action_type` (`action_type`),
  KEY `subject_guid` (`subject_guid`),
  KEY `object_guid` (`object_guid`),
  KEY `target_guid` (`target_guid`),
  KEY `annotation_id` (`annotation_id`),
  KEY `posted` (`posted`),
  KEY `access_guid` (`access_guid`),
  KEY `access_owner_guid` (`access_owner_guid`),
  KEY `access_id` (`access_id`),
  KEY `topic` (`topic`),
  KEY `type` (`type`),
  KEY `subtype` (`subtype`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;